//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLHelper.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TLHelper.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Akarats Champion ähnelt.
        /// </summary>
        internal static string akarats_champion {
            get {
                return ResourceManager.GetString("akarats_champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barbarian ähnelt.
        /// </summary>
        internal static string barb {
            get {
                return ResourceManager.GetString("barb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battle Rage ähnelt.
        /// </summary>
        internal static string battle_rage {
            get {
                return ResourceManager.GetString("battle_rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blinding Flash ähnelt.
        /// </summary>
        internal static string blinding_flash {
            get {
                return ResourceManager.GetString("blinding_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bone Armor ähnelt.
        /// </summary>
        internal static string bone_armor {
            get {
                return ResourceManager.GetString("bone_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breath of Heaven ähnelt.
        /// </summary>
        internal static string breath_of_heaven {
            get {
                return ResourceManager.GetString("breath_of_heaven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Call of the Ancients ähnelt.
        /// </summary>
        internal static string call_of_the_ancients {
            get {
                return ResourceManager.GetString("call_of_the_ancients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command Skeletons ähnelt.
        /// </summary>
        internal static string command_skeletons {
            get {
                return ResourceManager.GetString("command_skeletons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Companion ähnelt.
        /// </summary>
        internal static string companion {
            get {
                return ResourceManager.GetString("companion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Condemn ähnelt.
        /// </summary>
        internal static string condemn {
            get {
                return ResourceManager.GetString("condemn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crusader ähnelt.
        /// </summary>
        internal static string crus {
            get {
                return ResourceManager.GetString("crus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Death Nova ähnelt.
        /// </summary>
        internal static string death_nova {
            get {
                return ResourceManager.GetString("death_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Devour ähnelt.
        /// </summary>
        internal static string devour {
            get {
                return ResourceManager.GetString("devour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demon Hunter ähnelt.
        /// </summary>
        internal static string dh {
            get {
                return ResourceManager.GetString("dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diamond Skin ähnelt.
        /// </summary>
        internal static string diamond_skin {
            get {
                return ResourceManager.GetString("diamond_skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Energy Armor ähnelt.
        /// </summary>
        internal static string energy_armor {
            get {
                return ResourceManager.GetString("energy_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Epiphany ähnelt.
        /// </summary>
        internal static string epiphany {
            get {
                return ResourceManager.GetString("epiphany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Explosive Blast ähnelt.
        /// </summary>
        internal static string explosive_blast {
            get {
                return ResourceManager.GetString("explosive_blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Familiar ähnelt.
        /// </summary>
        internal static string familiar {
            get {
                return ResourceManager.GetString("familiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fan of Knives ähnelt.
        /// </summary>
        internal static string fan_of_knives {
            get {
                return ResourceManager.GetString("fan_of_knives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fetish Army ähnelt.
        /// </summary>
        internal static string fetish_army {
            get {
                return ResourceManager.GetString("fetish_army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frost Nova ähnelt.
        /// </summary>
        internal static string frost_nova {
            get {
                return ResourceManager.GetString("frost_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gargantuan ähnelt.
        /// </summary>
        internal static string gargantuan {
            get {
                return ResourceManager.GetString("gargantuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horrify ähnelt.
        /// </summary>
        internal static string horrify {
            get {
                return ResourceManager.GetString("horrify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ice Armor ähnelt.
        /// </summary>
        internal static string ice_armor {
            get {
                return ResourceManager.GetString("ice_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore Pain ähnelt.
        /// </summary>
        internal static string ignore_pain {
            get {
                return ResourceManager.GetString("ignore_pain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iron Skin ähnelt.
        /// </summary>
        internal static string iron_skin {
            get {
                return ResourceManager.GetString("iron_skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Land of the Dead ähnelt.
        /// </summary>
        internal static string land_of_the_dead {
            get {
                return ResourceManager.GetString("land_of_the_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laws of Hope ähnelt.
        /// </summary>
        internal static string laws_of_hope {
            get {
                return ResourceManager.GetString("laws_of_hope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laws of Justice ähnelt.
        /// </summary>
        internal static string laws_of_justice {
            get {
                return ResourceManager.GetString("laws_of_justice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laws of Valor ähnelt.
        /// </summary>
        internal static string laws_of_valor {
            get {
                return ResourceManager.GetString("laws_of_valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magic Weapon ähnelt.
        /// </summary>
        internal static string magic_weapon {
            get {
                return ResourceManager.GetString("magic_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mantra of Conviction ähnelt.
        /// </summary>
        internal static string mantra_of_conviction {
            get {
                return ResourceManager.GetString("mantra_of_conviction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mantra of Healing ähnelt.
        /// </summary>
        internal static string mantra_of_healing {
            get {
                return ResourceManager.GetString("mantra_of_healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mantra of Retribution ähnelt.
        /// </summary>
        internal static string mantra_of_retribution {
            get {
                return ResourceManager.GetString("mantra_of_retribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Massconfusion ähnelt.
        /// </summary>
        internal static string massconfusion {
            get {
                return ResourceManager.GetString("massconfusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monk ähnelt.
        /// </summary>
        internal static string monk {
            get {
                return ResourceManager.GetString("monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mystical Ally ähnelt.
        /// </summary>
        internal static string mystical_ally {
            get {
                return ResourceManager.GetString("mystical_ally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Necromancer ähnelt.
        /// </summary>
        internal static string nec {
            get {
                return ResourceManager.GetString("nec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overpower ähnelt.
        /// </summary>
        internal static string overpower {
            get {
                return ResourceManager.GetString("overpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Potion ähnelt.
        /// </summary>
        internal static string potion {
            get {
                return ResourceManager.GetString("potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preparation ähnelt.
        /// </summary>
        internal static string preparation {
            get {
                return ResourceManager.GetString("preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provoke ähnelt.
        /// </summary>
        internal static string provoke {
            get {
                return ResourceManager.GetString("provoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rain of Vengeance ähnelt.
        /// </summary>
        internal static string rain_of_vengeance {
            get {
                return ResourceManager.GetString("rain_of_vengeance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revenge ähnelt.
        /// </summary>
        internal static string revenge {
            get {
                return ResourceManager.GetString("revenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sacrifice ähnelt.
        /// </summary>
        internal static string sacrifice {
            get {
                return ResourceManager.GetString("sacrifice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serenity ähnelt.
        /// </summary>
        internal static string serenity {
            get {
                return ResourceManager.GetString("serenity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shadow Power ähnelt.
        /// </summary>
        internal static string shadow_power {
            get {
                return ResourceManager.GetString("shadow_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulacrum ähnelt.
        /// </summary>
        internal static string simulacrum {
            get {
                return ResourceManager.GetString("simulacrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skeletal Mages ähnelt.
        /// </summary>
        internal static string skeletal_mages {
            get {
                return ResourceManager.GetString("skeletal_mages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smoke Screen ähnelt.
        /// </summary>
        internal static string smoke_screen {
            get {
                return ResourceManager.GetString("smoke_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soul Harvest ähnelt.
        /// </summary>
        internal static string soul_harvest {
            get {
                return ResourceManager.GetString("soul_harvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprint ähnelt.
        /// </summary>
        internal static string sprint {
            get {
                return ResourceManager.GetString("sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storm Armor ähnelt.
        /// </summary>
        internal static string storm_armor {
            get {
                return ResourceManager.GetString("storm_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threatening Shout ähnelt.
        /// </summary>
        internal static string threatening_shout {
            get {
                return ResourceManager.GetString("threatening_shout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vengeance ähnelt.
        /// </summary>
        internal static string vengeance {
            get {
                return ResourceManager.GetString("vengeance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die War Cry ähnelt.
        /// </summary>
        internal static string war_cry {
            get {
                return ResourceManager.GetString("war_cry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Witch Doctor ähnelt.
        /// </summary>
        internal static string wd {
            get {
                return ResourceManager.GetString("wd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wizard ähnelt.
        /// </summary>
        internal static string wiz {
            get {
                return ResourceManager.GetString("wiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrath of the Berserker ähnelt.
        /// </summary>
        internal static string wrath_of_the_berserker {
            get {
                return ResourceManager.GetString("wrath_of_the_berserker", resourceCulture);
            }
        }
    }
}
